DrogNet/DrogNet/Controllers/NosotrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DrogNet.Controllers
{
    public class NosotrosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DrogNet/DrogNet/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DrogNet.Data;
using DrogNet.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using DrogNet.ViewModels;

namespace DrogNet.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment Hosting;
        public ProductoController(ApplicationDbContext context, IHostingEnvironment hosting)
        {
            _context = context;
            Hosting = hosting;
        }

        // GET: Producto
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Producto.Include(p => p.TipoMedicamento);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .Include(p => p.TipoMedicamento)
                .FirstOrDefaultAsync(m => m.ProductoID == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Producto/Create
        public IActionResult Create()
        {
            ViewData["TipoMedicamentoID"] = new SelectList(_context.TipoMedicamento, "TipoMedicamentoID", "TipoMedicamentoID");
            return View("ProductoViewModel");
        }

        // POST: Producto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductoViewModel producto)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (producto.Photo != null)
                {
                    string uploadsFolder = Path.Combine(Hosting.WebRootPath, "images");
                    uniqueFileName = $"{DateTime.Now.ToString("yyyyMMddHHmmss")}{producto.Photo.FileName}"; string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    producto.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                    Producto newDetalle = new Producto
                    {
                        TipoMedicamentoID = producto.TipoMedicamentoID,
                        Nombre = producto.Nombre,
                        Laboratorio = producto.Laboratorio,
                        Precio = producto.Precio,
                        Lote = producto.Lote,
                        FechaVencimiento = producto.FechaVencimiento,
                        PathFile = uniqueFileName
                    };
                    _context.Producto.Add(newDetalle); 
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index),new{ id = newDetalle.ProductoID });
                }
          
            }

            ViewData["TipoMedicamentoID"] = new SelectList(_context.TipoMedicamento, "TipoMedicamentoID", "Nombre", producto.TipoMedicamentoID);
            ViewData["ProductoID"] = new SelectList(_context.Set<Producto>(), "ProductoID", "Nombre", producto.ProductoID);
            return View(producto);
        }
        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["TipoMedicamentoID"] = new SelectList(_context.TipoMedicamento, "TipoMedicamentoID", "TipoMedicamentoID", producto.TipoMedicamentoID);
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductoID,Nombre,TipoMedicamentoID,Laboratorio,Precio,Lote,PathFile,FechaVencimiento")] Producto producto)
        {
            if (id != producto.ProductoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ProductoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoMedicamentoID"] = new SelectList(_context.TipoMedicamento, "TipoMedicamentoID", "TipoMedicamentoID", producto.TipoMedicamentoID);
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .Include(p => p.TipoMedicamento)
                .FirstOrDefaultAsync(m => m.ProductoID == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _context.Producto.FindAsync(id);
            _context.Producto.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.Producto.Any(e => e.ProductoID == id);
        }
    }
}

DrogNet/DrogNet/Controllers/QuejaSugerenciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DrogNet.Data;
using DrogNet.Models;

namespace DrogNet.Controllers
{
    public class QuejaSugerenciaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public QuejaSugerenciaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: QuejaSugerencia
        public async Task<IActionResult> Index()
        {
            return View(await _context.QuejaSugerencia.ToListAsync());
        }

        // GET: QuejaSugerencia/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quejaSugerencia = await _context.QuejaSugerencia
                .FirstOrDefaultAsync(m => m.QuejaSugerenciaID == id);
            if (quejaSugerencia == null)
            {
                return NotFound();
            }

            return View(quejaSugerencia);
        }

        // GET: QuejaSugerencia/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: QuejaSugerencia/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("QuejaSugerenciaID,Tema,Descripcion,Fecha")] QuejaSugerencia quejaSugerencia)
        {
            if (ModelState.IsValid)
            {
                _context.Add(quejaSugerencia);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quejaSugerencia);
        }

        // GET: QuejaSugerencia/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quejaSugerencia = await _context.QuejaSugerencia.FindAsync(id);
            if (quejaSugerencia == null)
            {
                return NotFound();
            }
            return View(quejaSugerencia);
        }

        // POST: QuejaSugerencia/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("QuejaSugerenciaID,Tema,Descripcion,Fecha")] QuejaSugerencia quejaSugerencia)
        {
            if (id != quejaSugerencia.QuejaSugerenciaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quejaSugerencia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuejaSugerenciaExists(quejaSugerencia.QuejaSugerenciaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(quejaSugerencia);
        }

        // GET: QuejaSugerencia/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quejaSugerencia = await _context.QuejaSugerencia
                .FirstOrDefaultAsync(m => m.QuejaSugerenciaID == id);
            if (quejaSugerencia == null)
            {
                return NotFound();
            }

            return View(quejaSugerencia);
        }

        // POST: QuejaSugerencia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quejaSugerencia = await _context.QuejaSugerencia.FindAsync(id);
            _context.QuejaSugerencia.Remove(quejaSugerencia);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuejaSugerenciaExists(int id)
        {
            return _context.QuejaSugerencia.Any(e => e.QuejaSugerenciaID == id);
        }
    }
}

DrogNet/DrogNet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DrogNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/jquery-ui.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">


    <link rel="stylesheet" href="css/aos.css">

    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <div class="site-navbar py-2">

            <div class="container">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="logo">
                        <div class="site-logo">
                            <a asp-controller="Home" asp-action="Index" class="js-logo-clone">Drognet</a>
                        </div>
                    </div>
                    <div class="main-nav d-none d-lg-block">
                        <nav class="site-navigation text-right text-md-center" role="navigation">
                            <ul class="site-menu js-clone-nav d-none d-lg-block">
                                <li class="active"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
                                <li><a asp-controller="Producto" asp-action="Index">Tienda</a></li>
                                <li><a asp-controller="Nosotros" asp-action="Index">Nosotros</a></li>
                                <li><a asp-controller="QuejaSugerencia" asp-action="Create">Contactenos</a></li>
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
                                    </li>
                                    <li class="nav-item">
                                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <button type="submit" class="nav-link btn btn-link text-dark">Cerrar Sesion</button>
                                        </form>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Registrarse</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Iniciar Sesion</a>
                                    </li>
                                }
                            </ul>
                        </nav>
                    </div>
                    <div class="icons">
                        <a href="cart.html" class="icons-btn d-inline-block bag">
                            <span class="icon-shopping-bag"></span>
                            <span class="number">2</span>
                        </a>
                        <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none">
                            <span class="icon-menu"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>




    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

                    <div class="block-7">
                        <h3 class="footer-heading mb-4">Sobre Nosotros</h3>
                        <p>Somos una compañía que esta a la vanguardia en farmacia Online y Call Center, nuestra prioridad, respeto absoluto por la formula médic</p>
                    </div>

                </div>
                <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
                    <h3 class="footer-heading mb-4">Enlaces rapidos</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Supplementos</a></li>
                        <li><a href="#">Vitaminas</a></li>
                        <li><a href="#">Cuidado Personal</a></li>
                        <li><a href="#">Belleza</a></li>
                    </ul>
                </div>

                <div class="col-md-6 col-lg-3">
                    <div class="block-5 mb-5">
                        <h3 class="footer-heading mb-4">Informacion</h3>
                        <ul class="list-unstyled">
                            <li class="address">Las Nieves - Tunja</li>
                            <li class="phone"><a href="tel://23923929210">+57 317 224 89 06</a></li>
                            <li class="email"></li>
                        </ul>
                    </div>


                </div>
            </div>
            <div class="row pt-5 mt-5 text-center">
                <div class="col-md-12">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> Todos los derechos reservados | Desarrollado
                        por Esteban Martinez <i class="icon-heart" aria-hidden="true"></i>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>

            </div>
        </div>
    </footer>
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/jquery-ui.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/aos.js"></script>

    <script src="js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>